### ISSUE TITLE
[Creator Starter Kit] BUG: Imort Solution Failed: Object reference is not set to an instance of an object

### ISSUE THREAD

**Issue by gerd-walter** [microsoft/powercat-creator-kit#219] opened 2022-12-13 16:59 UTC
Hi, on an exclusice CoE Environment we got an import error. It doesn't make a difference if we install it manually (solution import) or per App Source:

![image](https://user-images.githubusercontent.com/55480638/207395221-9e50edc1-4adf-46af-8c33-0305d69646ab.png)
![image](https://user-images.githubusercontent.com/55480638/207395418-6e85eb5a-57a8-4cb2-9b7b-73d2cdf5f721.png)
![image](https://user-images.githubusercontent.com/55480638/207395691-93ccfc26-def8-453a-a1cc-47b150f711c9.png)

Power Apps Component Framework is enabled:
![image](https://user-images.githubusercontent.com/55480638/207396272-7a535436-0a50-4db4-9bfb-3aa048f2fe52.png)

thanks in advance,
Gerd

**Comment by kapilmehtagit** [comment] 2022-12-13 17:01
Having the same issue. It did install successfully on a Developer environment in the Europe region, but on Production and Sandbox environment in the UK region it always fails, regardless of a direct import or app source based install.

**Comment by denisem-msft** [comment] 2022-12-13 21:34
Thank you for reporting this and apologies for the inconvenience.

This issue has been affecting multiple customers but has been intermittent and inconsistent with regions. We are actively looking into the root cause.

We will post to this thread with further updates once available.

**Comment by ashlega** [comment] 2022-12-14 14:23
It it helps... Was facing this issue in the Canada region last week. The product team deployed a patch over the weekend. Had no issues importing Creator Kit on Monday, Dec 12. Maybe it's now about having that deployment propagated through the regions (and I wonder if the original failure would propagate first followed by the fix?)

**Comment by ashculmsee** [comment] 2022-12-15 02:54
Also having this issue in Australia in a Production environment!

**Comment by UncleBoost** [comment] 2022-12-15 02:54
Me too - I'm in Australia

**Comment by waiholiu** [comment] 2022-12-15 03:26
broken in Australia and Hong Kong region

**Comment by swapp1012** [comment] 2022-12-15 07:06
Even in India region it is throwing same error

**Comment by garyfrostncc** [comment] 2022-12-15 08:44
> Having the same issue. It did install successfully on a Developer environment in the Europe region, but on Production and Sandbox environment in the UK region it always fails, regardless of a direct import or app source based install.

Same here in UK region

**Comment by kapilmehtagit** [comment] 2022-12-15 11:07
> It it helps... Was facing this issue in the Canada region last week. The product team deployed a patch over the weekend. Had no issues importing Creator Kit on Monday, Dec 12. Maybe it's now about having that deployment propagated through the regions (and I wonder if the original failure would propagate first followed by the fix?)

Would you happen to know what the patch update was about? Might provide a clue. Thanks

**Comment by ashlega** [comment] 2022-12-15 12:30
> Would you happen to know what the patch update was about? Might provide a clue. Thanks

Don't know such details, but, it seems, that same fix will be deployed over the coming weekend in the other regions (for what it's worth, though).

**Comment by medicineshow** [comment] 2022-12-16 15:45
I am having the same issue in UK South

**Comment by medicineshow** [comment] 2022-12-18 13:56
Appears to now be fixed in UK South

**Comment by fishyconnor** [comment] 2022-12-18 22:40
Fixed in Australia

**Comment by denisem-msft** [comment] 2022-12-20 23:28
A fix has been rolled out and should resolve this issue on all regions. Thanks to those who reported the issue and current status!

Closing this for now, but if anyone is still experiencing problems importing the latest Creator Kit release, please let us know by reactivating this thread.

**Closed by denisem-msft** 2022-12-20 23:28 UTC
Labels: bug, blocked
