### ISSUE TITLE
[BUG]: DetailsList not showing any data when published

### ISSUE THREAD

**Issue by lwak94** [microsoft/powercat-creator-kit#492] opened 2024-09-09 11:41 UTC
I am using the DetailsList component with a collection.
Until now everything worked well, unfortunately since an update the app is not showing any data when published.
In Power App Studio the list component is still working, but after a publish and play of the live version, no data is shown.

When rolling back to the last version (from August 2024), the app still works.

Just opening the app in power apps studio and publish (without any changes) the app will not show any data.
I think that has to do with the authoring version.

**To Reproduce**

1. Go to open app in edit -> "Power Apps Studio"
2. Click on Save
3. Publish App
4. Play App
5. Enter Search term
6. Navigate to Result Screen

**Expected behavior**
After the collection gets data, the app navigates automatically to the result screen.
Here the data from the collection must be visible. (Navigation still takes place, which means data is in collection)

**Additional context**

Tested authoring versions (non working):
- 3.24052.30 (current)
- 3.24081.10
- 3.24082.13
- 3.24083.14
- 3.24091.11

Additionally tested with studio version studio-version=v3.24052.30.298708436

Checked data via monitor -> Data is loaded correctly.

**Comment by MaheshSripada** [comment] 2024-09-10 11:07
Hi @lwak94,

We appreciate you bringing this to our attention. 

Unfortunately, I have tried to reproduce this issue in our environment by using collection with Search function in Formulas and  App.Start, then using this collection in the details list by changing the studio version to above, But could not reproduce it. 

Could you please provide more details about the issue? Specifically, we need [insert specific information needed, e.g., logs, screenshots, steps to reproduce]." 
To better understand the problem, can you provide 

1) The formula used for the collection.
2) Where are you updating / setting this collection (App Start or Named Formulas or On Visible of screen)
3) If any errors in the Monitor

This will help us resolve the issue more efficiently.

**Comment by lwak94** [comment] 2024-09-10 13:35
Hi,

Thanks for your help!

I was able to fix it by myself. It was indeed no bug within the powercat component.
MSFT just changed the behavior of empty textinput-fields - this was the issue!
An "Brakout" with !IsBlank(Textinput.value) did the job 🙂

So we can close this bug.

Thanks anyways and sorry for the inconvenience!


Mit freundlichen Grüßen | Best regards​​​​
Lorenzo Wakunda
Technology Consultant Microsoft Dynamics 365
[HSO]<https://www.hso.com/de/>
M +49 160 98006585<tel:+49%20160%2098006585>
T +49 7031 4903-0

________________________________

**Comment by MaheshSripada** [comment] 2024-09-11 09:14
We appreciate your kind words. If you need anything else, don’t hesitate to reach out. 
Closing this ticket as confirmed by you.

**Closed by MaheshSripada** 2024-09-11 09:14 UTC
Labels: bug, 👋 needs author feedback
