### ISSUE TITLE
[Creator Starter Kit] BUG: Theme Slot does not work properly

### ISSUE THREAD

**Issue by github129** [microsoft/powercat-creator-kit#38] opened 2022-06-10 08:21 UTC
**Describe the bug**
The close function does not work.
Scrolling will close the opened item.

**To Reproduce**
1. Launch Fluent Theme Designer
2. Scroll down to Theme slots
3. Click on Defaults

![image](https://user-images.githubusercontent.com/25972825/173022296-85d731ed-fab3-4145-be3b-280e555937ad.png)

**Expected behavior**
The Defaults accordion is closed.

**Screenshots**

![image](https://user-images.githubusercontent.com/25972825/173022296-85d731ed-fab3-4145-be3b-280e555937ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**
I used Creator Kit June 2022.
This bug has been confirmed from previous versions.

**Comment by denisem-msft** [comment] 2022-06-15 22:09
@github129 thanks for reporting this issue. I am able to reproduce this, it looks like the items under "Slot name" are being displayed even though the icon is not technically in an expanded state. If you "expand" the "slot name" column and then try collapsing the menus below, it will work as intended.
![image](https://user-images.githubusercontent.com/43950360/173940702-754017ed-2299-4a4f-9c96-731bc714fc8b.png)

**Comment by denisem-msft** [comment] 2022-10-11 22:42
This is not necessary for using the theme editor and does not disrupt the functionality of the tool. We can remove this section from the theme editor to avoid confusion but will address this based on resources available.

**Comment by adedaporh** [comment] 2023-01-02 01:16
> @github129 thanks for reporting this issue. I am able to reproduce this, it looks like the items under "Slot name" are being displayed even though the icon is not technically in an expanded state. If you "expand" the "slot name" column and then try collapsing the menus below, it will work as intended. ![image](https://user-images.githubusercontent.com/43950360/173940702-754017ed-2299-4a4f-9c96-731bc714fc8b.png)

But what exactly is supposed to be the behaviour here...
Is "Slot name" supposed to control the expansion and collapse of the sub-groups regardless of the state of those sub-groups? If that's the case, then it is clearly not working at all.
You also mentioned below, that this behaviour does not disrupt the functionality of the tool and I'm not sure I agree for 2 reasons:
1. As it is right now, I'm unable to explore the lower sub-groups such as _Inputs_ and _Lists_ because scrolling collapses them as the original post has mentioned.
2. It's not quite clear if the issue is with the implementation of the _DetailsList_ component used here or with the component itself. If it is with the component then I think a seperate issue needs to be raised.

**Comment by denisem-msft** [comment] 2023-01-03 21:52
I would argue that the core functionality of the Creator Kit tool is to generate the theme palette based on the three input colors provided, and our tool specifically generates a palette object that is usable in the Power Fx expression language (which is slightly different from the output provided in the actual [Fluent UI Theme Designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/).

When I say the functionality of the tool will not be affected, I mean the output of the tool will be the same, whether or not these collapsible menus are working. These menus are helpful for your own understanding of the values that are generated but interacting with these values will not change the value of the output theme.

You can use the real theme designer tool in the Fluent UI team's website and observe the values for your own learning by providing the same values you put into the Creator Kit theme designer: https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/

**Comment by denisem-msft** [comment] 2023-01-21 02:00
Closing this for now. Please reopen if the previous comment is not sufficient with reasoning behind why it's blocking you.

**Closed by denisem-msft** 2023-01-21 02:00 UTC
Labels: bug
