### ISSUE TITLE
[BUG]: Cannot import solution CreatorKitCore_1.0.20221205.2_managed.zip

### ISSUE THREAD

**Issue by mitadeo** [microsoft/powercat-creator-kit#214] opened 2022-12-06 22:27 UTC
I am trying to import the managed solution for CreatorKitCore_1.0.20221205.2_managed.zip and I am receiving the error:

Échec de l’importation de la solution « Creator Kit » : Import Solution Failed: Object reference not set to an instance of an object.

**To Reproduce**

- Select Import solution from menu
- Select managed solution zip file
- Select import
- See error, after a minute or so

**Expected behavior**
Solution imported with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/90434563/206037185-737d0c3e-8740-4694-8495-25b87b465e1e.png)

![image](https://user-images.githubusercontent.com/90434563/206472911-34046668-b0f5-4e83-b187-aaba822fd896.png)
![image](https://user-images.githubusercontent.com/90434563/206472223-b64f16e6-8552-4f3c-878b-5514f5bdfe75.png)

**Additional context**
Here is the XML file generated by the error
[Creator Kit_import.zip](https://github.com/microsoft/powercat-creator-kit/files/10170708/Creator.Kit_import.zip)

**Comment by highpar** [comment] 2022-12-09 18:59
I have same issue :(

**Comment by WinOnMarco** [comment] 2022-12-10 12:24
Experiencing the same.

**Comment by MJGiveItAGo** [comment] 2022-12-11 20:00
Experiencing the same

**Comment by justatheory** [comment] 2022-12-11 20:59
I'm experiencing the same. Tried both Upgrade and Update. 

**Update**
Import Solution Failed: Object reference not set to an instance of an object.

**Upgrade**
The imported solution and the existing solution must both be managed for upgrade.

**Comment by anjCerbolles** [comment] 2022-12-12 02:48
I am experiencing the same.

**Comment by highpar** [comment] 2022-12-12 12:16
Guys, I solved the problem as follows: In the environment settings, add the language 1033 (English), and wait a while until importing the solution again

**Comment by Hart365** [comment] 2022-12-12 16:45
My language is already 1033 but I am experiencing this issue as well. Tried it in various environments and tenants (US and UK based) and same result each time.

Some of the environments have a previous version installed, whilst others are completely clean.

**Comment by SPMush** [comment] 2022-12-12 20:39
Same issue, Language is UK English 
Import Solution Failed: Object reference not set to an instance of an object.

**Comment by Bari-Tech** [comment] 2022-12-13 01:07
Having the same issue. English language.
![image](https://user-images.githubusercontent.com/20613051/207201138-a6236c2c-afdd-47fb-aa7b-598cb51a2c8f.png)

**Comment by kapilmehtagit** [comment] 2022-12-13 15:15
Same error. It did import successfully in a Developer environment in the Europe region, but fails consistently in a Production or Sandbox environment in the UK region.

**Comment by denisem-msft** [comment] 2022-12-13 22:17
Thank you for reporting this and apologies for the inconvenience.

This issue has been affecting multiple customers but is also intermittent and inconsistent with regions. We are actively looking into the root cause.

We will post to this thread with further updates once available.

**Comment by SPMush** [comment] 2022-12-16 09:45
![image](https://user-images.githubusercontent.com/55295944/208070607-88e09632-d9c3-4636-9e89-1a04d77d8672.png)

**Comment by denisem-msft** [comment] 2022-12-20 23:35
A fix has been rolled out and should resolve this issue on all regions. Thanks to those who reported the issue and current status!

Closing this for now, but if anyone is still experiencing problems importing the latest Creator Kit release, please let us know by reactivating this thread.

**Closed by denisem-msft** 2022-12-20 23:35 UTC
Labels: bug, blocked
