### ISSUE TITLE
[BUG]: Black Background in Component Library Object Panel

### ISSUE THREAD

**Issue by Litoss90** [microsoft/powercat-creator-kit#295] opened 2023-03-06 12:33 UTC
When i want to use the Panel Component it has a Black Background.
Like in the Picture seen - it has also some Formula Errors

**To Reproduce**

Add Component from Library
Add to Canvas

**Expected behavior**
White Background

**Screenshots**
![FailureCreatorKit](https://user-images.githubusercontent.com/58888278/223111553-30ff65d7-d111-4287-b3f5-7731d27ed5c9.png)
![FailureCreatorKit2](https://user-images.githubusercontent.com/58888278/223111557-c062e12d-bf2e-460a-ac3e-355a46cff486.png)

**Comment by sakthi-sv** [comment] 2023-03-07 05:19
Hi,
I have also been facing similar issues but it's not just the Panel, I have been facing similar issues in all the Power Cat Component like Header, Dialog, Panel and Expand Menu, below is the screenshot of the same.

To reproduce the below error just import the components in the canvas app.

![image](https://user-images.githubusercontent.com/40761420/223324261-fc64688a-0858-4ca9-8cf1-234fd3db9865.png)
![image](https://user-images.githubusercontent.com/40761420/223325103-bbefadbc-ffc0-4420-bdb8-c7b4b23d458c.png)
![image](https://user-images.githubusercontent.com/40761420/223325237-06d84096-c000-47d7-98b6-c96d5e41699f.png)

The Expand Menu is the only exception, but it also has formula error.

![image](https://user-images.githubusercontent.com/40761420/223325481-230feaef-f037-4638-bc23-bd1220b379ed.png)

**Comment by winthermichael** [comment] 2023-03-10 08:16
Same issue here.

The issue exists for all objects in the component library.

Caused by the introduction of the new way of referencing elements like fonts and colors. Formulas used in the different objects in the component library needs to be updated to "Color.Transparant" and "Font.Segoe" rather than just "Transparant" and "Segoe".

Could the PowerCAT-team have a look at this? Pretty simple fix IMO.

**Comment by redbaron1974** [comment] 2023-03-10 14:31
Yep, I got the same issues.  This issue appears on these components Header, Dialog, Panel and Expand Menu.

**Comment by slaouist** [comment] 2023-03-14 16:10
Thanks for reporting this. We are looking into it and will fix as soon as possible.

**Comment by jgslc65** [comment] 2023-04-05 14:40
Are you able to provide an estimate of when this bug is likely to be resolved?  We have a Centre of Excellence installation scheduled in a couple of weeks and will need to postpone it if this issue is outstanding.  Any information would be much appreciated.  Many thanks.

**Comment by denise-msft** [comment] 2023-04-06 16:30
> Are you able to provide an estimate of when this bug is likely to be resolved? We have a Centre of Excellence installation scheduled in a couple of weeks and will need to postpone it if this issue is outstanding. Any information would be much appreciated. Many thanks.

@jgslc65 we are planning on releasing a fix mid-april that will address this. Thank you for your patience and apologies for the inconvenience.

**Comment by mikefactorial** [comment] 2023-04-14 13:43
@Litoss90 This has been fixed in the latest release.

**Closed by mikefactorial** 2023-04-14 13:43 UTC
Labels: bug, canvas

**Comment by jgslc65** [comment] 2023-04-17 12:33
> @Litoss90 This has been fixed in the latest release.

Thank you.  When will this fix be available as a managed solution?

**Comment by JaKovac87** [comment] 2023-04-28 08:45
Is there an solution available for with this fix?

**Comment by denise-msft** [comment] 2023-05-01 15:30
@JaKovac87 @jgslc65 please install the latest release from the downloads in the april release: https://github.com/microsoft/powercat-creator-kit/releases/tag/CreatorKit-April2023
