### ISSUE TITLE
(Picker) Resize event is not fired in model-driven app custom pages

### ISSUE THREAD

**Issue by scottdurow** [microsoft/powercat-creator-kit#182] opened 2022-09-14 23:02 UTC
When a TagPicker is used in model-driven custom pages, the AutoHeight property is not updated to reflect the new height when the control resizes due to a tag being added/removed or the control width is being changed. This works correctly in a canvas app.

1. Open the model-driven app and canvas app reference apps side by side (in the player-studio does not show the issue)
2. Add or remove the tags as shown below and notice that the content below the tag picker does not move to allow space for the picker.
3. 
Appears to be caused by flex-box styles added by custom pages differently to canvas apps.

More information https://github.com/microsoft/powercat-creator-kit/issues/97

**Comment by denisem-msft** [comment] 2023-01-21 00:44
Can you still reproduce this? Autoheight seems to be working when I tested  it:

Figure 1: Autowidth = 63.1875
![image](https://user-images.githubusercontent.com/43950360/213829822-9d439069-eeca-47ca-916f-8df1ad8d9e75.png)

Figure 2: Autowidth = 94.79 when I reduce screen size triggering responsive wrap
![image](https://user-images.githubusercontent.com/43950360/213829888-cfbb214b-d1f0-4b59-9227-567a3e3ce5c2.png)

Closing for now, but please reopen if you are still seeing this or if I missed something.

**Closed by denisem-msft** 2023-01-21 00:44 UTC
Labels: bug
