### ISSUE TITLE
Cannot install latest update as current and new solutions must both be managed [Creator Starter Kit] BUG:

### ISSUE THREAD

**Issue by mjburley** [microsoft/powercat-creator-kit#218] opened 2022-12-13 10:48 UTC
Current environment (DataVerse used for Centre of Excellence).

Creator kit installed for latest CoE update (as per link on MS docs). Version 1.0.20221102.3.
![image](https://user-images.githubusercontent.com/67462615/207296904-b5c8143b-0518-4f3d-ba04-13919bfec970.png)

Required different version for use in CoE, so tried to install latest release from github. CreatorKitCore_1.0.20221205.2_managed.

![image](https://user-images.githubusercontent.com/67462615/207297220-f828c13e-fc0e-4bfe-ab07-78395b4cd2d9.png)

This results in the following error.
The imported solution and the existing solution must both be managed for upgrade.
![image](https://user-images.githubusercontent.com/67462615/207297354-3ec15338-9ec3-44f9-8547-8ea4b2345543.png)

Log file attached
[Creator Kit_import (1).log](https://github.com/microsoft/powercat-creator-kit/files/10217074/Creator.Kit_import.1.log)

**Comment by denisem-msft** [comment] 2022-12-13 21:34
Thank you for reporting this and apologies for the inconvenience.

This issue has been affecting multiple customers but has been intermittent and inconsistent with regions. We are actively looking into the root cause.

We will post to this thread with further updates once available.

**Comment by denisem-msft** [comment] 2022-12-13 21:37
@mjburley did you try to delete the unmanaged solution and then import the managed solution?

**Comment by mjburley** [comment] 2022-12-14 10:08
Yes, I deleted the original and tried re-importing. New error message:

Import Solution Failed: Object reference not set to an instance of an object.

**Comment by justatheory** [comment] 2022-12-15 22:20
I'm also getting this error when selecting Upgrade. This is despite the installed Creator Kit solution and new version both being managed. If select the Update option I get the Object reference not set to an instance of an object message. I'm in New Zealand (Aus region). Cheers, Dean Moran.

**Comment by denisem-msft** [comment] 2022-12-20 23:31
@mjburley @justatheory Install should work now, please try again and let me know if you have any issues.

I'm closing the thread, but please reopen if you do still have issues..

**Closed by denisem-msft** 2022-12-20 23:31 UTC
Labels: bug, needs author feedback
